<script setup lang="ts">
import { computed, onMounted, shallowRef } from 'vue'
import { getImageSettings, saveImageSettings, type ImageSettings, type ImageModel } from '../../api/imageGeneration'
const props = defineProps<{ providerId: string }>()
const settings = shallowRef<ImageSettings>({ models: [], default_id: '' })
const busy = shallowRef(false), error = shallowRef(''), notice = shallowRef('')
const models = computed(() => settings.value.models.filter(model => model.provider_id === props.providerId))
onMounted(async () => { try { settings.value = await getImageSettings() } catch (cause) { error.value = String(cause) } })
function add() { settings.value = { ...settings.value, models: [...settings.value.models, { id: crypto.randomUUID(), provider_id: props.providerId, model: '', protocol: 'images', size: 'auto', quality: 'auto', streaming: false, enabled: true }] } }
function update(id: string, changes: Partial<ImageModel>) { settings.value = { ...settings.value, models: settings.value.models.map(model => model.id === id ? { ...model, ...changes } : model) } }
function remove(id: string) { settings.value = { ...settings.value, models: settings.value.models.filter(model => model.id !== id) } }
async function save() { busy.value = true; error.value = ''; notice.value = ''; try { settings.value = await saveImageSettings(settings.value); notice.value = '生图模型已保存，URL 和 Key 复用当前服务商。' } catch (cause) { error.value = String(cause) } finally { busy.value = false } }
</script>
<template>
  <section class="image-model-settings"><header><div><h3>生图模型</h3><p>与聊天模型分开选择，复用本服务商的 URL 和 Key。</p></div><button class="settings-command" :disabled="busy" @click="add">添加生图模型</button></header>
    <div v-for="model in models" :key="model.id" class="image-model-row">
      <div class="image-model-main"><input type="checkbox" :checked="model.enabled" :aria-label="`启用生图模型 ${model.model}`" @change="update(model.id, { enabled: ($event.target as HTMLInputElement).checked })" /><input class="model-name" :value="model.model" placeholder="填写生图模型 ID" aria-label="生图模型 ID" @input="update(model.id, { model: ($event.target as HTMLInputElement).value })" /><button :class="{ default: settings.default_id === model.id }" @click="settings = { ...settings, default_id: model.id }">{{ settings.default_id === model.id ? '默认' : '设为默认' }}</button><button @click="remove(model.id)">移除</button></div>
      <div class="image-model-options"><label>协议<select :value="model.protocol" @change="update(model.id, { protocol: ($event.target as HTMLSelectElement).value as ImageModel['protocol'] })"><option value="images">Images API</option><option value="responses">Responses API</option></select></label><label>尺寸<input :value="model.size" placeholder="auto / 1536x1024" @input="update(model.id, { size: ($event.target as HTMLInputElement).value })" /></label><label>质量<select :value="model.quality" @change="update(model.id, { quality: ($event.target as HTMLSelectElement).value })"><option v-for="quality in ['auto','low','medium','high','xhigh','max']" :key="quality" :value="quality">{{ quality }}</option></select></label><label class="stream-checkbox"><input type="checkbox" :checked="model.streaming" @change="update(model.id, { streaming: ($event.target as HTMLInputElement).checked })" />接口支持中间图</label></div>
      <label v-if="model.protocol === 'responses'" class="request-model">Responses 主模型<input :value="model.request_model" placeholder="负责调用生图工具的对话模型 ID" @input="update(model.id, { request_model: ($event.target as HTMLInputElement).value })" /></label>
    </div>
    <footer v-if="models.length || settings.models.length"><button class="settings-command" :disabled="busy" @click="save">{{ busy ? '保存中…' : '保存生图配置' }}</button><span>{{ notice }}</span></footer><p v-if="error" role="alert" class="image-model-error">{{ error }}</p>
  </section>
</template>
<style scoped>
.image-model-settings { border-top: 1px solid var(--settings-line); padding-top: 20px; display: grid; gap: 14px; }.image-model-settings header { display: flex; justify-content: space-between; align-items: center; gap: 16px; }.image-model-settings h3 { margin: 0; font-size: 14px; font-weight: 550; }.image-model-settings p { margin: 5px 0 0; color: var(--settings-muted); font-size: 11px; }.image-model-row { padding: 12px 0; border-bottom: 1px solid var(--settings-line); }.image-model-main { display: flex; align-items: center; gap: 9px; }.image-model-main .model-name { flex: 1; min-width: 80px; }.image-model-main button { border: 0; background: none; color: var(--settings-muted); cursor: pointer; font-size: 11px; }.image-model-main button.default { color: #c3914e; }.image-model-options { display: flex; flex-wrap: wrap; gap: 12px; margin-top: 12px; }.image-model-options label,.request-model { display: flex; align-items: center; gap: 7px; color: var(--settings-muted); font-size: 11px; }.image-model-options input:not([type=checkbox]) { width: 100px; }.image-model-settings input:not([type=checkbox]),.image-model-settings select { background: var(--settings-field); color: var(--settings-text); border: 1px solid var(--settings-line); border-radius: 5px; padding: 6px 8px; font-size: 12px; }.request-model { margin-top: 10px; }.request-model input { flex: 1; }.image-model-settings footer { display: flex; gap: 12px; align-items: center; font-size: 11px; color: var(--settings-muted); }.image-model-error { color: #c8645d !important; }
</style>
